name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

template: |
  ## What’s Changed
  $CHANGES

categories:
  - type: pre-exclude
    when:
      labels:
        - 'skip-changelog'
  - title: '🦑 Features'
    semver-increment: minor
    when:
      labels:
        - 'enhancement'
        - 'feature'
  - title: '💔 Breaking Changes'
    semver-increment: major
    when:
      labels:
        - 'breaking-change'
  - title: '🐛 Bug Fixes'
    when:
      labels:
        - 'bug'
        - 'bugfix'
        - 'fix'
  - title: '🧰 Maintenance'
    when:
      labels:
        - 'chore'
        - 'documentation'
        - 'dependencies'
  - type: version-resolver
    semver-increment: major
    when:
      labels:
        - 'major'
  - type: version-resolver
    semver-increment: minor
    when:
      labels:
        - 'minor'
  - type: version-resolver # No 'when' means the default increment
    semver-increment: patch

category-template: '### $TITLE'
change-template: '- $TITLE by @$AUTHOR in #$NUMBER'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

autolabeler:
  - label: 'enhancement'
    branch: [ '/^feature\//', '/^feat\//' ]
  - label: 'bug'
    branch: [ '/^fix\//', '/^hotfix\//' ]
  - label: 'chore'
    branch: [ '/^chore\//' ]
  - label: 'skip-changelog'
    branch: [ '/^release\//' ]
